spring:
  kafka:
      consumer:
        properties:
          spring.json.trusted.packages: '*'
  cloud:
    function:
      definition: consumer
    stream:
      kafka:
        bindings:
          consumer-in-0:
            consumer:
              configuration:
                value.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        binder:
          brokers: localhost:9092
      bindings:
        consumer-in-0:
          destination : javainuse