spring:
  kafka:
      consumer:
        properties:
          spring.json.trusted.packages: '*'
          spring.json.value.default.type: com.spring.training.model.Message
          spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
  cloud:
    function:
      definition: consumer

    stream:
      kafka:
        bindings:
          consumer-in-0:
            consumer:
              configuration:
                value.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
        binder:
          brokers: localhost:9092
      bindings:
        consumer-in-0:
          destination : javainuse